# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: SendEmail@0
  inputs:
    To: 'dbaker6@gaig.com'
    From: 'derek.m.baker@gmail.com'
    Subject: 'test'
    Body: 'test'
    SmtpServer: 'smtp.gmail.com'
    SmtpPort: '587'
    SmtpUsername: 'Derek.m.baker@gmail.com'
    SmtpPassword: 'BlueFish85'
    STARTTLS: TRUE

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
